export type AtlasSlaContractProfile = {
  key: string;
  category: string;
  customerType: string;
  durationMonths: string;
  warrantyMonths: string;
  phoneSupport: string;
  preventiveOnsite: string;
  extraordinaryOnsite: string;
  sparePartsIncluded: string;
  blockingResponse: string;
  nonblockingResponse: string;
  pickupShipping: string;
  serviceHours: string;
  serviceDays: string;
  driveLink: string;
  commercialNotes: string;
  summary: string;
  aliases: string;
  keywords: string;
  matchPriority: number;
  parentCustomer: string;
  childCustomers: string;
  isActive: boolean;
};

export const SLA_CONTRACT_FIELDS: Array<{
  key: keyof AtlasSlaContractProfile;
  label: string;
  rows?: number;
  wide?: boolean;
}> = [
  { key: "category", label: "Categoria Cliente" },
  { key: "customerType", label: "Tipologia Cliente", wide: true },
  { key: "parentCustomer", label: "Cliente padre" },
  { key: "childCustomers", label: "Clienti / figli / sedi collegate", rows: 3, wide: true },
  { key: "durationMonths", label: "Durata contratto (mesi)" },
  { key: "warrantyMonths", label: "Garanzia (mesi)" },
  { key: "phoneSupport", label: "Assistenza telefonica" },
  { key: "preventiveOnsite", label: "Intervento preventivo on site / ordinaria manutenzione", rows: 3, wide: true },
  { key: "extraordinaryOnsite", label: "Intervento straordinario on site / su chiamata", rows: 3, wide: true },
  { key: "sparePartsIncluded", label: "Parti di ricambio incluse - escluso consumabili", rows: 3, wide: true },
  { key: "blockingResponse", label: "Risposta guasto bloccante" },
  { key: "nonblockingResponse", label: "Risposta anomalia non bloccante" },
  { key: "pickupShipping", label: "Servizio di ritiro e spedizione" },
  { key: "serviceHours", label: "Orario di servizio" },
  { key: "serviceDays", label: "Giorni di servizio" },
  { key: "driveLink", label: "Link dettaglio contratto / Drive Secom", rows: 2, wide: true },
  { key: "commercialNotes", label: "Note commerciali", rows: 4, wide: true },
  { key: "summary", label: "Riassunto operativo", rows: 4, wide: true },
  { key: "aliases", label: "Alias ricerca", rows: 3, wide: true },
  { key: "keywords", label: "Keyword match", rows: 3, wide: true },
  { key: "matchPriority", label: "Priorità match" },
];

export const SLA_BASE_CONTRACT_PROFILES: AtlasSlaContractProfile[] = [
  {
    key: "ministero-questure",
    category: "MINISTERO DELL'INTERNO",
    customerType: "QUESTURE",
    parentCustomer: "MINISTERO DELL'INTERNO",
    childCustomers: "Questure",
    durationMonths: "N/D",
    warrantyMonths: "N/D",
    phoneSupport: "N/D",
    preventiveOnsite: "N/D",
    extraordinaryOnsite: "N/D",
    sparePartsIncluded: "N/D",
    blockingResponse: "N/D",
    nonblockingResponse: "N/D",
    pickupShipping: "N/D",
    serviceHours: "N/D",
    serviceDays: "N/D",
    driveLink: "N/D",
    commercialNotes: "",
    summary: "Profilo ministeriale generico. Dati SLA da verificare su contratto specifico.",
    aliases: "ministero, questure, questura, interno",
    keywords: "ministero interno questure",
    matchPriority: 50,
    isActive: true,
  },
  {
    key: "ministero-ps-lazio-umbria",
    category: "MINISTERO DELL'INTERNO",
    customerType: "PS LAZIO/UMBRIA",
    parentCustomer: "MINISTERO DELL'INTERNO",
    childCustomers: "PS Lazio; PS Umbria",
    durationMonths: "N/D",
    warrantyMonths: "N/D",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI",
    sparePartsIncluded: "SI (fino a 100,00 € per lampade, UPS, numeratore, scheda elettronica SPIS)",
    blockingResponse: "N/D",
    nonblockingResponse: "N/D",
    pickupShipping: "N/D",
    serviceHours: "N/D",
    serviceDays: "N/D",
    driveLink: "N/D",
    commercialNotes: "",
    summary: "Assistenza telefonica e straordinaria attiva; ricambi coperti fino a soglia indicata.",
    aliases: "ps lazio, ps umbria, polizia stato lazio, polizia stato umbria",
    keywords: "ps lazio umbria",
    matchPriority: 70,
    isActive: true,
  },
  {
    key: "polizia-frontiera-spis-my",
    category: "MINISTERO DELL'INTERNO",
    customerType: "POLIZIA DI FRONTIERA Fornitura 2025 / SPIS MY",
    parentCustomer: "MINISTERO DELL'INTERNO",
    childCustomers: "Polizia di Frontiera",
    durationMonths: "36",
    warrantyMonths: "24",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI",
    sparePartsIncluded: "SI",
    blockingResponse: "12 ORE",
    nonblockingResponse: "24 ORE",
    pickupShipping: "SI",
    serviceHours: "9:00-18:00 e Sabato 9:00-13:00",
    serviceDays: "Lun-Sab fino alle 13:00",
    driveLink: "",
    commercialNotes: "",
    summary: "Contratto Frontiere SPIS MY con assistenza telefonica, straordinaria, ricambi e ritiro/spedizione inclusi.",
    aliases: "frontiere, polizia frontiera, spis my frontiere",
    keywords: "frontiera frontiere spis my",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "polizia-ferroviaria-spis-my",
    category: "MINISTERO DELL'INTERNO",
    customerType: "POLIZIA FERROVIARIA Fornitura 2026 / SPIS MY",
    parentCustomer: "MINISTERO DELL'INTERNO",
    childCustomers: "Polizia Ferroviaria; POLFER",
    durationMonths: "24",
    warrantyMonths: "24",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI",
    sparePartsIncluded: "SI",
    blockingResponse: "7",
    nonblockingResponse: "14",
    pickupShipping: "SI",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Contratto POLFER SPIS MY: ricambi, intervento straordinario e ritiro/spedizione inclusi.",
    aliases: "polfer, polizia ferroviaria, spis my",
    keywords: "polfer ferroviaria spis my",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "hotspot-albania-2024-2026",
    category: "MINISTERO DELL'INTERNO",
    customerType: "HOTSPOT ALBANIA 2024-2026",
    parentCustomer: "MINISTERO DELL'INTERNO",
    childCustomers: "Hotspot Albania",
    durationMonths: "24",
    warrantyMonths: "SCADUTA",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI",
    sparePartsIncluded: "SI",
    blockingResponse: "5",
    nonblockingResponse: "10",
    pickupShipping: "SI",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Hotspot Albania: garanzia scaduta, assistenza telefonica e straordinaria attive.",
    aliases: "albania, hotspot albania",
    keywords: "hotspot albania",
    matchPriority: 70,
    isActive: true,
  },
  {
    key: "carabinieri-provinciali-gruppo-vecchio-spis",
    category: "CARABINIERI",
    customerType: "CARABINIERI PROVINCIALI/GRUPPO VECCHIO SPIS contratto triennale 2024-2026",
    parentCustomer: "CARABINIERI",
    childCustomers: "Comandi Provinciali; Gruppi Carabinieri",
    durationMonths: "12",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "SI, solo Comandi Provinciali e Gruppo",
    extraordinaryOnsite: "SI, previa autorizzazione dell'uff. AES",
    sparePartsIncluded: "Decurtabili fino a 80K € annui, per determinati componenti come da nota allegata",
    blockingResponse: "7?",
    nonblockingResponse: "14?",
    pickupShipping: "SI",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Vecchio SPIS per Provinciali/Gruppi: manutenzione preventiva prevista solo per Comandi Provinciali e Gruppi; straordinaria previa autorizzazione AES.",
    aliases: "carabinieri provinciali, comando provinciale carabinieri, gruppo carabinieri, com prov cc",
    keywords: "carabinieri provinciale gruppo vecchio spis",
    matchPriority: 95,
    isActive: true,
  },
  {
    key: "carabinieri-compagnie-vecchio-spis",
    category: "CARABINIERI",
    customerType: "CARABINIERI COMPAGNIE VECCHIO SPIS contratto triennale 2024-2026",
    parentCustomer: "CARABINIERI",
    childCustomers: "Compagnie Carabinieri; Tenenze; Stazioni se agganciate a Compagnia",
    durationMonths: "12",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI, previa autorizzazione dell'uff. AES",
    sparePartsIncluded: "Decurtabili fino a 80K € annui, per determinati componenti come da nota allegata",
    blockingResponse: "7?",
    nonblockingResponse: "14?",
    pickupShipping: "SI",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Vecchio SPIS per Compagnie: nessuna preventiva, straordinaria previa autorizzazione AES, ricambi decurtabili dal plafond.",
    aliases: "compagnia carabinieri, comp cc, comp. cc, tenenza carabinieri, stazione carabinieri",
    keywords: "carabinieri compagnie vecchio spis",
    matchPriority: 100,
    isActive: true,
  },
  {
    key: "carabinieri-nuovo-spis-my",
    category: "CARABINIERI",
    customerType: "CARABINIERI NUOVO SPIS MY - PENISOLA ESCLUSA",
    parentCustomer: "CARABINIERI",
    childCustomers: "Nuovo SPIS MY Carabinieri",
    durationMonths: "24",
    warrantyMonths: "24",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI",
    sparePartsIncluded: "SI",
    blockingResponse: "7?",
    nonblockingResponse: "14?",
    pickupShipping: "SI",
    serviceHours: "08:30/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Nuovo SPIS MY Carabinieri con 24 mesi di garanzia, ricambi e spedizione inclusi.",
    aliases: "carabinieri nuovo spis my",
    keywords: "carabinieri nuovo spis my",
    matchPriority: 90,
    isActive: true,
  },
  {
    key: "comuni-polizia-locale",
    category: "COMUNI",
    customerType: "POLIZIA LOCALE/MUNICIPALE/PROVINCIALE",
    parentCustomer: "COMUNI",
    childCustomers: "Polizia Locale; Polizia Municipale; Polizia Provinciale",
    durationMonths: "12/24/36",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "SI, nr. 2 annuali, 1 a semestre",
    extraordinaryOnsite: "SI, nr. 1 annuale",
    sparePartsIncluded: "SI",
    blockingResponse: "Non definito < 5gg",
    nonblockingResponse: "Non definito < 10gg",
    pickupShipping: "SI",
    serviceHours: "9:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Comuni/Polizie locali: due preventive annuali, una straordinaria annuale, ricambi e spedizione inclusi.",
    aliases: "comuni, polizia locale, polizia municipale, polizia provinciale",
    keywords: "comuni polizia locale municipale provinciale",
    matchPriority: 90,
    isActive: true,
  },
  {
    key: "estero-san-marino-gendarmeria",
    category: "ESTERO",
    customerType: "SAN MARINO - GENDARMERIA",
    parentCustomer: "ESTERO",
    childCustomers: "San Marino; Gendarmeria",
    durationMonths: "12",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "SI, nr. 2 annuali, 1 a semestre",
    extraordinaryOnsite: "SI, nr. 1 annuale",
    sparePartsIncluded: "SI",
    blockingResponse: "Non definito < 5gg",
    nonblockingResponse: "Non definito < 10gg",
    pickupShipping: "SI",
    serviceHours: "9:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "Gendarmeria San Marino: preventive semestrali, straordinaria annuale, ricambi inclusi.",
    aliases: "san marino, gendarmeria",
    keywords: "san marino gendarmeria",
    matchPriority: 80,
    isActive: true,
  },
  {
    key: "rfi-aula-sepa",
    category: "RFI",
    customerType: "AULA SEPA",
    parentCustomer: "RFI",
    childCustomers: "Aula SEPA",
    durationMonths: "48",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "SI, nr. 2 annuali, 1 a semestre",
    extraordinaryOnsite: "SI",
    sparePartsIncluded: "SI (ad esclusione di quanto riportato nell'allegato)",
    blockingResponse: "2",
    nonblockingResponse: "7",
    pickupShipping: "SI",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "RFI Aula SEPA: SLA stretto, preventive semestrali, ricambi secondo allegato.",
    aliases: "rfi, aula sepa, sepa",
    keywords: "rfi aula sepa",
    matchPriority: 90,
    isActive: true,
  },
  {
    key: "rfi-webvime",
    category: "RFI",
    customerType: "WEBVIME",
    parentCustomer: "RFI",
    childCustomers: "Webvime",
    durationMonths: "12",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "SI, come da allegato contratto",
    sparePartsIncluded: "NO",
    blockingResponse: "—",
    nonblockingResponse: "—",
    pickupShipping: "—",
    serviceHours: "8:00 - 18:00",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "WEBVIME: assistenza telefonica e straordinaria secondo allegato, ricambi esclusi.",
    aliases: "webvime, rfi webvime",
    keywords: "webvime rfi",
    matchPriority: 95,
    isActive: true,
  },
  {
    key: "pa-privato-smartfad",
    category: "PA/PRIVATO",
    customerType: "SMARTFAD care-pack",
    parentCustomer: "PA/PRIVATO",
    childCustomers: "SmartFAD",
    durationMonths: "12/24/36",
    warrantyMonths: "—",
    phoneSupport: "SI",
    preventiveOnsite: "NO",
    extraordinaryOnsite: "NO",
    sparePartsIncluded: "SI",
    blockingResponse: "7",
    nonblockingResponse: "14",
    pickupShipping: "SI",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "SmartFAD care-pack: ricambi e spedizione inclusi, nessun intervento on-site programmato.",
    aliases: "smartfad, care pack, pa privato",
    keywords: "smartfad care-pack",
    matchPriority: 75,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-genova",
    category: "PORTI",
    customerType: "SEEKS/BEESCO GENOVA",
    parentCustomer: "PORTI",
    childCustomers: "Genova",
    durationMonths: "12",
    warrantyMonths: "12",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:27",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Genova: preventiva inclusa, straordinaria non obbligatoria, sostituzione componenti danneggiate.",
    aliases: "porti, seeks, beesco, genova",
    keywords: "seeks beesco genova porti",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-trieste",
    category: "PORTI",
    customerType: "SEEKS/BEESCO TRIESTE",
    parentCustomer: "PORTI",
    childCustomers: "Trieste",
    durationMonths: "36",
    warrantyMonths: "36",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:28",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Trieste: garanzia 36 mesi, preventiva inclusa, sostituzione sole componenti danneggiate.",
    aliases: "porti, seeks, beesco, trieste",
    keywords: "seeks beesco trieste porti",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-savona-t2",
    category: "PORTI",
    customerType: "SEEKS/BEESCO SAVONA T2",
    parentCustomer: "PORTI",
    childCustomers: "Savona T2",
    durationMonths: "24",
    warrantyMonths: "24",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:29",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Savona T2: garanzia 24 mesi, preventiva inclusa, sostituzione componenti danneggiate.",
    aliases: "porti, seeks, beesco, savona t2",
    keywords: "seeks beesco savona t2 porti",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-savona-t1",
    category: "PORTI",
    customerType: "SEEKS/BEESCO SAVONA T1",
    parentCustomer: "PORTI",
    childCustomers: "Savona T1",
    durationMonths: "24",
    warrantyMonths: "24",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Savona T1: garanzia 24 mesi, preventiva inclusa, sostituzione componenti danneggiate.",
    aliases: "porti, seeks, beesco, savona t1",
    keywords: "seeks beesco savona t1 porti",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-civitavecchia-vespucci-arrivi",
    category: "PORTI",
    customerType: "SEEKS/BEESCO CIVITAVECCHIA VESPUCCI ARRIVI",
    parentCustomer: "PORTI",
    childCustomers: "Civitavecchia Vespucci Arrivi",
    durationMonths: "12",
    warrantyMonths: "12",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:31",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Civitavecchia Vespucci Arrivi: garanzia 12 mesi, preventiva inclusa.",
    aliases: "porti, seeks, beesco, civitavecchia, vespucci arrivi",
    keywords: "seeks beesco civitavecchia vespucci arrivi porti",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-civitavecchia-vespucci-partenze",
    category: "PORTI",
    customerType: "SEEKS/BEESCO CIVITAVECCHIA VESPUCCI PARTENZE",
    parentCustomer: "PORTI",
    childCustomers: "Civitavecchia Vespucci Partenze",
    durationMonths: "12",
    warrantyMonths: "12",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:32",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Civitavecchia Vespucci Partenze: garanzia 12 mesi, preventiva inclusa.",
    aliases: "porti, seeks, beesco, civitavecchia, vespucci partenze",
    keywords: "seeks beesco civitavecchia vespucci partenze porti",
    matchPriority: 85,
    isActive: true,
  },
  {
    key: "porti-seeeks-beesco-civitavecchia-bramante",
    category: "PORTI",
    customerType: "SEEKS/BEESCO CIVITAVECCHIA BRAMANTE",
    parentCustomer: "PORTI",
    childCustomers: "Civitavecchia Bramante",
    durationMonths: "12",
    warrantyMonths: "12",
    phoneSupport: "SI",
    preventiveOnsite: "SI",
    extraordinaryOnsite: "NON OBBLIGATORIO",
    sparePartsIncluded: "Sostituzione delle sole componenti danneggiate",
    blockingResponse: "2",
    nonblockingResponse: "4",
    pickupShipping: "SI",
    serviceHours: "08:30/17:33",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "Parti guaste coperte da garanzia non includono l'intervento tecnico se non previsto da contratto. Costi di spedizione a carico del cliente.",
    summary: "PORTI Civitavecchia Bramante: garanzia 12 mesi, preventiva inclusa.",
    aliases: "porti, seeks, beesco, civitavecchia, bramante",
    keywords: "seeks beesco civitavecchia bramante porti",
    matchPriority: 85,
    isActive: true,
  },
];

export function createEmptySlaContractProfile(): AtlasSlaContractProfile {
  return {
    key: `custom-${Date.now()}`,
    category: "",
    customerType: "",
    parentCustomer: "",
    childCustomers: "",
    durationMonths: "",
    warrantyMonths: "",
    phoneSupport: "SI",
    preventiveOnsite: "",
    extraordinaryOnsite: "",
    sparePartsIncluded: "",
    blockingResponse: "",
    nonblockingResponse: "",
    pickupShipping: "",
    serviceHours: "09:00/17:30",
    serviceDays: "Lun-Ven (festivi esclusi)",
    driveLink: "",
    commercialNotes: "",
    summary: "",
    aliases: "",
    keywords: "",
    matchPriority: 50,
    isActive: true,
  };
}

export function contractCell(value: unknown) {
  return String(value ?? "").replaceAll("\n", " ").trim();
}

export function buildSlaContractExportRows(contractsToExport: AtlasSlaContractProfile[]) {
  const headers = SLA_CONTRACT_FIELDS.map((field) => field.label);

  const rows = contractsToExport.map((contract) =>
    SLA_CONTRACT_FIELDS.map((field) => contractCell(contract[field.key])),
  );

  return { headers, rows };
}

export function escapeHtml(value: unknown) {
  return contractCell(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
