import type {
  AtlasContract,
  AtlasInventoryItem,
  AtlasMaterial,
  AtlasTicketCategory,
  AtlasTicketStatus,
} from "./atlasTypes";

export const INITIAL_BUDGET = 49043;

export const materials: AtlasMaterial[] = [
  { id: "kit-tlc", name: "Kit TLC", cost: 931 },
  { id: "uccs", name: "UCCS", cost: 821 },
  { id: "monitor", name: "Monitor", cost: 199 },
  { id: "kit-lampade", name: "Kit lampade", cost: 72 },
  { id: "ram", name: "RAM", cost: 56 },
  { id: "hub-usb", name: "Hub USB", cost: 52 },
  { id: "motore-sedia", name: "Motore sedia SPIS", cost: 196 },
  { id: "ups", name: "UPS", cost: 94 },
  { id: "tastiera-mouse", name: "Tastiera e mouse", cost: 31 },
  { id: "numeratore", name: "Circuito numeratore SPIS", cost: 199 },
  { id: "ssd-500", name: "SSD 500GB", cost: 92 },
];

export const technicians = [
  "Andrea Fabbri",
  "Ivan Canossi",
  "Francesco Romano",
  "Christian Appolloni",
  "Giuseppe Marafioti",
  "Leonardo Aureli",
];

export const ticketCategoryOptions: {
  value: AtlasTicketCategory;
  label: string;
  hint: string;
}[] = [
  { value: "ordinaria", label: "Ordinaria", hint: "Non scala budget" },
  { value: "straordinaria", label: "Straordinaria", hint: "Scala budget" },
  { value: "garanzia", label: "In garanzia", hint: "Intervento coperto" },
  {
    value: "materiale",
    label: "Materiale fornito/sostituito",
    hint: "Ricambio o fornitura",
  },
];

export const ticketStatusOptions: { value: AtlasTicketStatus; label: string }[] = [
  { value: "nuova", label: "Nuova" },
  { value: "pianificata", label: "Pianificata" },
  { value: "in lavorazione", label: "In lavorazione" },
  { value: "chiusa", label: "Chiusa" },
  { value: "in sospeso", label: "In sospeso" },
];

export const atlasStatusToDbStatus: Record<AtlasTicketStatus, string> = {
  nuova: "Aperto",
  pianificata: "Pianificato",
  "in lavorazione": "In lavorazione",
  chiusa: "Chiuso",
  "in sospeso": "In sospeso",
};

export const contracts: AtlasContract[] = [
  {
    name: "POLFER SPIS",
    match: ["POLFER", "POLIZIA FERROVIARIA"],
    clientType: "Polizia Ferroviaria",
    status: "Attivo",
    period: "Fornitura SPIS",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 90,
    pdf: "",
    warranty: "Sì",
    shipping: "Sì, se previsto da garanzia",
    spareParts: "Ricambi gestibili secondo contratto",
    sla: "7 giorni bloccante / 14 giorni non bloccante",
    notes:
      "Assistenza su apparati SPIS Polfer. Verificare sempre se la parte richiesta è coperta da garanzia o ricambio contrattuale.",
  },
  {
    name: "FRONTIERE 26 SPIS",
    match: ["FRONTIERA", "POLIZIA DI FRONTIERA"],
    clientType: "Polizia di Frontiera",
    status: "Attivo",
    period: "2024-2026",
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    renewalAlertDays: 120,
    pdf: "",
    warranty: "24 mesi",
    shipping: "Inclusa",
    spareParts: "Ripristino e sostituzione apparati inclusi",
    sla: "12 ore bloccante / 24 ore non bloccante",
    notes: "Trasporto, ritiro e sostituzione apparati inclusi nel contratto.",
  },
  {
    name: "HOTSPOT ALBANIA 2024-2026",
    match: ["ALBANIA", "HOTSPOT"],
    clientType: "Estero",
    status: "Attivo",
    period: "2024-2026",
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    renewalAlertDays: 120,
    pdf: "",
    warranty: "24 mesi",
    shipping: "Inclusa",
    spareParts: "Riparazione o sostituzione inclusa",
    sla: "5 giorni bloccante / 10 giorni non bloccante",
    notes: "Ritiro apparati, trasporto e supporto tecnico inclusi.",
  },
  {
    name: "CARABINIERI ASSISTENZA 2024-2026",
    match: [
      "CARABINIERI",
      "COMANDO PROVINCIALE",
      "GRUPPO CC",
      "REPARTO TERRITORIALE CC",
      "COMANDO GRUPPO",
    ],
    clientType: "Carabinieri",
    status: "Attivo",
    period: "2024-2026",
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    renewalAlertDays: 120,
    pdf: "",
    warranty: "Sì",
    shipping: "Sì previa autorizzazione",
    spareParts: "Ricambi inclusi entro limiti contrattuali",
    sla: "7 giorni bloccante / 14 giorni non bloccante",
    notes: "Interventi e ricambi soggetti ad autorizzazione AES.",
  },
  {
    name: "CC 75 SPIS",
    match: ["CC 75", "75 SPIS"],
    clientType: "Carabinieri",
    status: "Attivo",
    period: "Fornitura 75 SPIS",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 90,
    pdf: "",
    warranty: "Sì",
    shipping: "Da verificare",
    spareParts: "Gestibili secondo garanzia apparato",
    sla: "Da contratto specifico",
    notes: "Supporto su apparati SPIS della fornitura 75 postazioni.",
  },
  {
    name: "POLIZIE LOCALI",
    match: [
      "POLIZIA LOCALE",
      "POLIZIA MUNICIPALE",
      "POLIZIA PROVINCIALE",
      "COMUNE",
    ],
    clientType: "Polizia Locale / Comuni",
    status: "Attivo se contratto sottoscritto",
    period: "12/24/36 mesi",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 60,
    pdf: "",
    warranty: "Secondo contratto",
    shipping: "Se previsto",
    spareParts: "Secondo formula commerciale",
    sla: "5 giorni / 10 giorni",
    notes: "Verificare sempre formula commerciale sottoscritta dal Comune.",
  },
  {
    name: "RFI AULE SEPA",
    match: ["RFI", "AULA SEPA", "SEPA"],
    clientType: "RFI",
    status: "Attivo",
    period: "48 mesi",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 120,
    pdf: "",
    warranty: "Sì",
    shipping: "Inclusa",
    spareParts: "Incluse salvo esclusioni",
    sla: "2 giorni bloccante / 7 giorni non bloccante",
    notes: "Assistenza su Aule SEPA RFI con SLA prioritari.",
  },
  {
    name: "RFI WEBVIME",
    match: ["WEBVIME"],
    clientType: "RFI / Webvime",
    status: "Attivo",
    period: "12 mesi",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 60,
    pdf: "",
    warranty: "Sì",
    shipping: "Non applicabile",
    spareParts: "Software",
    sla: "Secondo allegato contratto",
    notes: "Assistenza software Webvime.",
  },
  {
    name: "SMARTFAD CARE-PACK",
    match: ["SMARTFAD"],
    clientType: "SmartFAD",
    status: "Attivo se Care-Pack sottoscritto",
    period: "12/24/36 mesi",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 60,
    pdf: "",
    warranty: "Copertura danni accidentali",
    shipping: "Andata cliente / ritorno Secom",
    spareParts: "Riparazione o sostituzione",
    sla: "5 giorni lavorativi",
    notes: "Esclusi furto, manomissioni, danni dolosi e uso improprio.",
  },
  {
    name: "SEEKS / BEESCO PORTI",
    match: ["SEEKS", "BEESCO", "PORTI", "TERMINAL", "VESPUCCI"],
    clientType: "Porti / EES",
    status: "Attivo",
    period: "12/24/36 mesi",
    startDate: "Da verificare",
    endDate: "Da verificare",
    renewalAlertDays: 90,
    pdf: "",
    warranty: "On-center",
    shipping: "Inclusa se in garanzia",
    spareParts: "Riparazione o sostituzione gratuita",
    sla: "2 giorni bloccante / 4 giorni non bloccante",
    notes: "Fuori garanzia serve valutazione tecnica e offerta economica.",
  },
];

export const initialInventory: AtlasInventoryItem[] = [
  { id: "KIT-TLC", name: "Kit TLC", value: 931, quantity: 0 },
  { id: "UCCS", name: "UCCS", value: 821, quantity: 0 },
  { id: "MONITOR", name: "Monitor", value: 199, quantity: 0 },
  { id: "KIT-LAMP", name: "Kit lampade", value: 72, quantity: 0 },
  { id: "RAM", name: "RAM", value: 56, quantity: 0 },
  { id: "HUB-USB", name: "Hub USB", value: 52, quantity: 0 },
  { id: "MOTORE-SPIS", name: "Motore sedia SPIS", value: 196, quantity: 0 },
  { id: "UPS", name: "UPS", value: 94, quantity: 0 },
  { id: "TAST-MOUSE", name: "Tastiera e mouse", value: 31, quantity: 0 },
  { id: "NUMERATORE", name: "Circuito numeratore SPIS", value: 199, quantity: 0 },
  { id: "SSD-500", name: "SSD 500GB", value: 92, quantity: 0 },
];
